#Project: IoT Wine Rack
#Authors: PJ
#Version: 0.0.1
#Date: 3/20/2019
#Changelog found in workspace

#Import supporting rack scripts
import lights

#Import all of the necessary Firestore packages
import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore

#Initiate the proper credentials
cred = credentials.Certificate('iotrack-firebase-adminsdk.json')
firebase_admin.initialize_app(cred)

#Establish connection to firestore
db = firestore.client()

##Rack light functions
#

##Pressure sensor functions


#EXAMPLE FIRESTORE FUNCTIONS
#Initiate a db variable
#users -> collection name, janesonswag -> document title within collection (can be autogenerated if blank I think)
doc_ref = db.collection(u'users').documents(u'janesonswag')
#Create a record at the doc_ref users/janesonsswag location
#This returns the update time for the action
doc_ref.set({
    u'first_name': "Paj",
    u'last_name': "Janeson"
})

#Retrieving information from firestore
#Set a db reference within the right level for users
users_ref = db.collection(u'users')
#Retrieve all of the information at the db reference
docs = users_ref.get()

for doc in docs:
    print (u'{} => {}'.format(doc.id, doc.to_dict()))